app.version=1.0.0

spring.datasource.url=jdbc:postgresql://10.0.9.182:5432/probas
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.port=8081